version: '3.6'

services:
  db:
      image: postgres:14.5-alpine
      container_name: db
      volumes:
        - ../data/db:/var/lib/postgresql/data:z
      environment:
        - POSTGRES_DB=hitalent
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 5432:5432
  frontend:
      build: ui
      container_name: frontend
      volumes:
        - ./ui/ht_ui:/var/www/ui
        - ./ui/ui.conf:/etc/apache2/sites-available/000-default.conf
        - ./ui/ui.sh:/var/www/ui.sh
      ports:
        - "80:80"
        - "443:443"
      command: server
  backend:
    build: services
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./services:/var/www/backend
      - ../feedback/screenshots:/var/www/backend/files:z
      - ../logs/server:/var/log/apache2:z
    depends_on:
      - db
