import { create } from "zustand";

const useStore = create((set) => ({
  userData: {
    email: "",
    name: "",
  },
  setUserData: (userData) => set(() => ({ userData })),
  //////////////////////////////////////////////////////////////////
  openViewAs: false,
  scrollViewAs: "",
  openAddParentPath: false,
  notAuthorised: false,
  getPathBool: false,
  newPathName: "",
  whoami: "",
  name: "",
  email: "",
  talentId: "",
  treeData: [],
  itd: [],
  tips: [],
  resources: [],
  selectedTaskKey: "",
  selectedTaskName: "",
  onClickShowStatus: false,
  doubleClickStatus: false,
  showSaveTree: false,
  showSaveTreeNodeData: false,
  selectedNewTaskName: "",
  skill: "",
  currentSkill: "",
  newSkill: "",
  newPoints: "",
  points: "",
  currentPoints: "",
  selectedTaskPoints: "",
  skillSet: [],
  getSkillBool: false,
  getTipBool: false,
  getResourceBool: false,
  getPointBool: false,
  showTreeData: false,
  taskSkills: "",
  completedPaths: "",
  currentProgress: "",
  progressChange: "",
  getCompletedPathsBool: false,
  selectLang: "",
  currentLang: "",
  currentTrack: "",
  selectTrack: "",
  stepsList: {},
  levelProgress: "",
  getProgressBool: false,
  profileName: "",
  profileEmail: "",
  talents: [],
  reload: false,
  ptId: "",
  showProgress: false,
  setOpenViewAs: (openViewAs) => set(() => ({ openViewAs })),
  setScrollViewAs: (scrollViewAs) => set(() => ({ scrollViewAs })),
  setOpenAddParentPath: (openAddParentPath) =>
    set(() => ({ openAddParentPath })),
  setNotAuthorised: (notAuthorised) => set(() => ({ notAuthorised })),
  setGetPathBool: (getPathBool) => set(() => ({ getPathBool })),
  setNewPathName: (newPathName) => set(() => ({ newPathName })),
  setWhoami: (whoami) => set(() => ({ whoami })),
  setTreeData: (treeData) => set(() => ({ treeData })),
  setItd: (itd) => set(() => ({ itd })),
  setTips: (tips) => set(() => ({ tips })),
  setResources: (resources) => set(() => ({ resources })),
  setTalentId: (talentId) => set(() => ({ talentId })),
  setName: (name) => set(() => ({ name })),
  setEmail: (email) => set(() => ({ email })),
  setSelectedTaskKey: (selectedTaskKey) => set(() => ({ selectedTaskKey })),
  setSelectedTaskName: (selectedTaskName) => set(() => ({ selectedTaskName })),
  setDoubleClickStatus: (doubleClickStatus) =>
    set(() => ({ doubleClickStatus })),
  setOnClickShowStatus: (onClickShowStatus) =>
    set(() => ({ onClickShowStatus })),
  setShowSaveTree: (showSaveTree) => set(() => ({ showSaveTree })),
  setShowSaveTreeNodeData: (showSaveTreeNodeData) =>
    set(() => ({ showSaveTreeNodeData })),
  setSelectedNewTaskName: (selectedNewTaskName) =>
    set(() => ({ selectedNewTaskName })),
  setSkill: (skill) => set(() => ({ skill })),
  setSkillSet: (skillSet) => set(() => ({ skillSet })),
  setCurrentSkill: (currentSkill) => set(() => ({ currentSkill })),
  setNewSkill: (newSkill) => set(() => ({ newSkill })),
  setPoints: (points) => set(() => ({ points })),
  setCurrentPoints: (currentPoints) => set(() => ({ currentPoints })),
  setNewPoints: (newPoints) => set(() => ({ newPoints })),
  setGetSkillBool: (getSkillBool) => set(() => ({ getSkillBool })),
  setGetTipBool: (getTipBool) => set(() => ({ getTipBool })),
  setGetResourceBool: (getResourceBool) => set(() => ({ getResourceBool })),
  setGetPointBool: (getPointBool) => set(() => ({ getPointBool })),
  setShowTreeData: (showTreeData) => set(() => ({ showTreeData })),
  setSelectedTaskPoints: (selectedTaskPoints) =>
    set(() => ({ selectedTaskPoints })),
  setTaskSkills: (taskSkills) => set(() => ({ taskSkills })),
  setCompletedPaths: (completedPaths) => set(() => ({ completedPaths })),
  setCurrentProgress: (currentProgress) => set(() => ({ currentProgress })),
  setProgressChange: (progressChange) => set(() => ({ progressChange })),
  setGetCompletedPathsBool: (getCompletedPathsBool) =>
    set(() => ({ getCompletedPathsBool })),
  setSelectLang: (selectLang) => set(() => ({ selectLang })),
  setCurrentLang: (currentLang) => set(() => ({ currentLang })),
  setCurrentTrack: (currentTrack) => set(() => ({ currentTrack })),
  setSelectTrack: (selectTrack) => set(() => ({ selectTrack })),
  setStepsList: (stepsList) => set(() => ({ stepsList })),
  setLevelProgress: (levelProgress) => set(() => ({ levelProgress })),
  setGetProgressBool: (getProgressBool) => set(() => ({ getProgressBool })),
  setProfileName: (profileName) => set(() => ({ profileName })),
  setProfileEmail: (profileEmail) => set(() => ({ profileEmail })),
  setTalents: (talents) => set(() => ({ talents })),
  setReload: (reload) => set(() => ({ reload })),
  setPtiD: (ptId) => set(() => ({ ptId })),
  setShowProgress: (showProgress) => set(() => ({ showProgress })),
}));

export default useStore;
