version: "3.8"

services:
  postgres:
    image: postgres:12.16
    container_name: hitalent
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DEV_DB},${POSTGRES_PROD_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

