version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_PROD_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../postgres-data:/var/lib/postgresql/data

  nodejs-app:
    build: ../server
    container_name: server
    ports:
      - "8000:8000"
    env_file:
      - ../server/.env
    depends_on:
      - postgres
